name: SkyCoreAC
version: '1.1.0'
main: dev.skycoreac.SkyCoreAC
api-version: '1.21'
description: High-accuracy anticheat for Paper 1.21.x
authors: [SkyCoreAC]

commands:
  skycoreac:
    description: SkyCoreAC main command
    aliases: [eac, eclipse]
    usage: /skycoreac <reload|alerts|info|reset|kick|version>
    permission: skycoreac.admin

permissions:
  skycoreac.admin:
    description: Access to all SkyCoreAC commands
    default: op
  skycoreac.alerts:
    description: Receive violation alerts in chat
    default: op
  skycoreac.bypass:
    description: Bypass all SkyCoreAC checks
    default: false
